plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ly.pet'
    compileSdk 35

    defaultConfig {
        applicationId "com.ly.pet"
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    // 暂时不加任何依赖，用最基础的
}
